apiVersion: v1
kind: Pod
metadata:
  name: noe-selector
  labels: 
    purpose: "selector-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx
    